# Generated by Django 5.1.7 on 2025-03-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_datapoint_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
